const main = async () => {
    console.log('HL');
}

main().catch((error) => {
    console.error('Error starting getting data', error);
  });